# Generated by Django 5.1.4 on 2025-01-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='team',
            field=models.TextField(default=None),
        ),
    ]
