# Generated by Django 5.2 on 2025-04-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contactinfo_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
